-- update total of orderTicketID 1 to $11 (Make sure to do select ALONE first)
-- select * from orderTicket 
-- 	where ID = 1
-- ;
-- update orderTicket 
-- 	set total = 90.95
--     where ID = 1
-- ;
-- -- delete from category
-- 	where id = 7
-- ;

